### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by kvishnivetsky**
id param to servers config
event_names param for event filtering (not implemented in Asterisk manager versions < 11)

### CODE REVIEW

**Comment by staskobzar** [comment]
Thank you. Merged.

**Comment by staskobzar** [comment]
The test ```test/test_config.c``` does not pass. Can you take a look and fix, please?
```
1..16
ok 1 - config_file_does_not_exists
ok 2 - config_file_with_invalid_int_value
not ok 3 - config_file_with_single_host
# Test failed with exception: Segmentation fault(11)
not ok 4 - config_file_with_multiple_hosts
# Test failed with exception: Segmentation fault(11)
not ok 5 - config_file_test_default_vals
# Test failed with exception: Segmentation fault(11)
ok 6 - config_file_with_missing_password
ok 7 - config_file_with_missing_name
ok 8 - config_file_with_missing_host
ok 9 - config_file_with_missing_username
not ok 10 - config_file_with_single_host_connection_address
# Test failed with exception: Segmentation fault(11)
not ok 11 - config_file_with_multiple_hosts_connection_address
# Test failed with exception: Segmentation fault(11)
not ok 12 - config_file_test_default_vals_connection_address
# Test failed with exception: Segmentation fault(11)
not ok 13 - config_file_web_root_set
# Test failed with exception: Segmentation fault(11)
not ok 14 - config_file_test_default_vals_for_web_root
# Test failed with exception: Segmentation fault(11)
ok 15 - config_file_auth_no_domain
ok 16 - config_file_auth_no_file
# not ok - Configuration file
```

**Comment by kvishnivetsky** [comment]
Ok. I'll do.I suppose, that I fogot to update sample config file.-------------------------------------------------С уввжением,Константин С. Вишнивецкий
-------- Исходное сообщение --------От: Stas Kobzar <notifications@github.com> Дата: 28.05.20  19:41  (GMT+07:00) Кому: staskobzar/amiws <amiws@noreply.github.com> Копия: "Konstantin S. Vishnivetsky" <reports@vishnivetsky.ru>, Author <author@noreply.github.com> Тема: Re: [staskobzar/amiws] Added some features (#11) 
The test test/test_config.c does not pass. Can you take a look and fix, please?
1..16
ok 1 - config_file_does_not_exists
ok 2 - config_file_with_invalid_int_value
not ok 3 - config_file_with_single_host
# Test failed with exception: Segmentation fault(11)
not ok 4 - config_file_with_multiple_hosts
# Test failed with exception: Segmentation fault(11)
not ok 5 - config_file_test_default_vals
# Test failed with exception: Segmentation fault(11)
ok 6 - config_file_with_missing_password
ok 7 - config_file_with_missing_name
ok 8 - config_file_with_missing_host
ok 9 - config_file_with_missing_username
not ok 10 - config_file_with_single_host_connection_address
# Test failed with exception: Segmentation fault(11)
not ok 11 - config_file_with_multiple_hosts_connection_address
# Test failed with exception: Segmentation fault(11)
not ok 12 - config_file_test_default_vals_connection_address
# Test failed with exception: Segmentation fault(11)
not ok 13 - config_file_web_root_set
# Test failed with exception: Segmentation fault(11)
not ok 14 - config_file_test_default_vals_for_web_root
# Test failed with exception: Segmentation fault(11)
ok 15 - config_file_auth_no_domain
ok 16 - config_file_auth_no_file
# not ok - Configuration file


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/staskobzar/amiws/pull/11#issuecomment-635325476",
"url": "https://github.com/staskobzar/amiws/pull/11#issuecomment-635325476",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kvishnivetsky** [comment]
> 
> 
> The test `test/test_config.c` does not pass. Can you take a look and fix, please?
> 
> ```
> 1..16
> ok 1 - config_file_does_not_exists
> ok 2 - config_file_with_invalid_int_value
> not ok 3 - config_file_with_single_host
> # Test failed with exception: Segmentation fault(11)
> not ok 4 - config_file_with_multiple_hosts
> # Test failed with exception: Segmentation fault(11)
> not ok 5 - config_file_test_default_vals
> # Test failed with exception: Segmentation fault(11)
> ok 6 - config_file_with_missing_password
> ok 7 - config_file_with_missing_name
> ok 8 - config_file_with_missing_host
> ok 9 - config_file_with_missing_username
> not ok 10 - config_file_with_single_host_connection_address
> # Test failed with exception: Segmentation fault(11)
> not ok 11 - config_file_with_multiple_hosts_connection_address
> # Test failed with exception: Segmentation fault(11)
> not ok 12 - config_file_test_default_vals_connection_address
> # Test failed with exception: Segmentation fault(11)
> not ok 13 - config_file_web_root_set
> # Test failed with exception: Segmentation fault(11)
> not ok 14 - config_file_test_default_vals_for_web_root
> # Test failed with exception: Segmentation fault(11)
> ok 15 - config_file_auth_no_domain
> ok 16 - config_file_auth_no_file
> # not ok - Configuration file
> ```

I run make check and it passed:
============================================================================
Testsuite summary for amiws 2.2.1
============================================================================
# TOTAL: 80
# PASS:  80
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

How run those test, which are not passed?

**Comment by staskobzar** [comment]
You are right, Konstantin.
This is probably my local Linux packages problem. It does pass on my other machine.
I am sorry for the trouble. Thanks for feedback and the contribution.

Have a good day!

**Pull request merged**
